# -*- coding: utf-8 -*-
"""session-1-tasks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14MlVcxF5pYArlyBHwF79P6kq8MpDHDj8

# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**: 
```
"Data" "Science" "Mentorship" "Program" 
"By" "CampusX"
```
**Output**: 
``` 
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]
"""

# Write your code here

st1 = "Data" 
st2 = "Science" 
st3= "Mentorship" 
st4 = "Program" 
st5 = "By" 
st6 = "CampusX"

print(st1,st2,st3, st4, sep = '-', end='-started-')
print(st5,st6, sep = '-')

"""### Q2:- Write a program that will convert celsius value to fahrenheit."""

# Write your code here
print("Celsius to fahrenheit conversion")

celsius = float(input("Enter the temperature in celsius: "))

fahrenheit = celsius * (9/5) + 32

print(f"The fahrenheit equivalent of {celsius} celsius is {fahrenheit} fahrenheit")

"""### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax."""

# Write your code here

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))

print(f"The original a & b before swap are: {a}, {b}")

temp = b
b = a
a = temp

print(f"The original a & b after swap are: {a}, {b}")

"""### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input."""

# Write your code here
print("Calculating euclidean distance given two coordinates")

print("Specify the first coordinate")
x1 = int(input("First coordinate (x1): "))
y1 = int(input("First coordinate (y1): "))

print("Specify the second coordinate")
x2 = int(input("Second coordinate (x2): "))
y2 = int(input("Second coordinate (y2): "))

distance = round(((x1 - x2)**2 + (y1 - y2)**2) ** 0.5,2)

print(f"The euclidean distance between ({x1},{y1}) and ({x2},{y2}) is {distance}")

"""### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

"""

# Write your code here
print("Calculate simple interest")

principle = float(input("Enter the principle amount (Rs): "))
roi = float(input("Enter the annual rate of interest (%): "))
time = int(input("Enter the time period (years): "))

simple_interest = round(principle * roi*time/100,2)

print(f"The simple interest on a principle of {principle} amount over a period of {time} years at annual interest of {roi}% = {simple_interest} ")

"""### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2




"""

# Write your code here
print("Number of dogs and chickens from total heads and legs calculation")

heads = int(input("Enter the total heads: "))
legs = int(input("Enter the total legs: "))

dogs = int((legs - 2 * heads)/2)
chicken = heads - dogs

print(f"There are a total of {dogs} dogs and {chicken} chickens")

"""### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user."""

# Write your code here
print("The sum of squares of first n natural numbers")

n = int(input("Enter the number: "))

sum_of_squares = n * (n+1) * (2*n+1)/6

print(f"The sum of squares of first {n} natural numbers is: {sum_of_squares}")

"""### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user."""

# Write your code here
print("Finding Nth term of the Arithmetic series")

first_number = int(input("Enter the first number: "))
second_number = int(input("Enter the second number: "))

difference = second_number - first_number

nth_term = int(input("Enter the Nth number: "))

nth_number = first_number + (nth_term - 1) * difference

print(f"The Nth term of an Arithmetic series with numbers starting at {first_number} and {second_number} is {nth_number}")

"""### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user."""

# Write your code here
print("Define the first fraction")
num_1 = float(input("Enter the numerator of first fraction: "))
den_1 = float(input("Enter the denominator of first fraction: "))

first_number = num_1/den_1

num_2 = float(input("Enter the numerator of second fraction: "))
den_2 = float(input("Enter the denominator of second fraction: "))

second_number = num_2/den_2

sum_of_fraction = round(first_number + second_number,3)

print(f"The sum of fractions are: {sum_of_fraction}")

"""### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm
"""

# Write your code here
print("Specify the dimension of the milk tank")
height = float(input("Enter the height of the tank (cms.): "))
length = float(input("Enter the length of the tank (cms.): "))
breadth = float(input("Enter the breadth of the tank (cms.): "))

volume_milk_tank = height * length * breadth

print("Specify the dimension of the glass")
height_g = float(input("Enter the height of the glass (cms.): "))
radius_g = float(input("Enter the radius of the glass (cms.): "))

volume_glass = (22/7) * height_g * (radius_g**2)

no_of_glasses = round(volume_milk_tank/volume_glass)

print(f"Glasses that can be filled with milk from milk tank: {no_of_glasses}")

